### ISSUE TITLE
Error: No matching indices found: No indices match "logstash-04-*"

### ISSUE THREAD

**Issue by csgaee** [JouniMi/TheDFIRThing#3]
![image](https://github.com/user-attachments/assets/b1f40c25-eaff-4257-b819-9993dc2d0aff)
![image](https://github.com/user-attachments/assets/3dbaeae1-8571-44ec-b0d8-c01f0d9ebde0)
create index for "logstash-04-*"

**Comment by JouniMi** [comment]
Crap, I may have forgotten to get rid of the index pattern matching that. :) I'll try to remember fixing it next time I am working on this either by removing the index pattern completely or just creating the index as suggested. That particular index is used when random JSON file is ingested so it makes likely more sense to remove the index pattern completely as it will be created automatically when data is ingested.

Anyway, even if the errors are given the tool should function perfectly normal but I do think that it makes it more clean if I just fix this.

**Comment by JouniMi** [comment]
This should be fixed now.
